x-logging: &default-logging
  logging:
    driver: json-file
    options:
      max-size: 100M

services:
  mongo:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db
    networks:
      - cce

  api:
    build:
      context: ./server
      dockerfile: Dockerfile
    restart: always
    env_file:
      - ./server/.env
    ports:
      - '3000:3000'
    networks:
      - cce
    depends_on:
      - mongo

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    restart: always
    command: npm run host
    env_file:
      - ./client/.env
    ports:
      - '5173:5173'
    networks:
      - cce

  server:
    image: judge0/judge0:1.13.1
    volumes:
      - ./judge0.conf:/judge0.conf:ro
    ports:
      - '2358:2358'
    privileged: true
    <<: *default-logging
    restart: always

  workers:
    image: judge0/judge0:1.13.1
    command: ['./scripts/workers']
    volumes:
      - ./judge0.conf:/judge0.conf:ro
    privileged: true
    <<: *default-logging
    restart: always

  db:
    image: postgres:16.2
    env_file: judge0.conf
    volumes:
      - data:/var/lib/postgresql/data/
    <<: *default-logging
    restart: always

  redis:
    image: redis:7.2.4
    command:
      [
        'bash',
        '-c',
        'docker-entrypoint.sh --appendonly no --requirepass "$$REDIS_PASSWORD"',
      ]
    env_file: judge0.conf
    <<: *default-logging
    restart: always

volumes:
  data:
  mongo_data:
networks:
  cce:
    driver: bridge
